[build]
command = "npm run build"
publish = "dist"

# Environment variables for different contexts
[context.production.environment]
VITE_RECAPTCHA_SITE_KEY = "6Leyim8rAAAAAINSXyIYn8xtPeOH-7sTB2-fBcNh"

# Handle single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200