[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.1"
  VITE_FIREBASE_API_KEY = "AIzaSyBtq7Z6qqaVmb22d3aNcwNiqkrbGtIhJ7g"
  VITE_FIREBASE_AUTH_DOMAIN = "mat1-9e6b3.firebaseapp.com"
  VITE_FIREBASE_DATABASE_URL = "https://mat1-9e6b3-default-rtdb.firebaseio.com"
  VITE_FIREBASE_PROJECT_ID = "mat1-9e6b3"
  VITE_FIREBASE_STORAGE_BUCKET = "mat1-9e6b3.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "250085264089"
  VITE_FIREBASE_APP_ID = "1:250085264089:web:51c2b209e0265e7d04ccc8"
  VITE_FIREBASE_MEASUREMENT_ID = "G-YHQHSJN5CQ"
  VITE_MOBILESERVICE_APP_ID = "1:250085264089:android:eddb5bd08de0b1b604ccc8"
  VITE_MOBILESERVICE_PACKAGE_NAME = "matmobile.com"
  VITE_MOBILESERVICE_API_KEY = "AIzaSyDNk9iW1PTGM9hvcjJ0utBABs7ZiWCj3Xc"
  VITE_CONTAINER_IMAGE = "africa-south1-docker.pkg.dev/mat1-9e6b3/cloud-run-source-deploy/maps@sha256:5c17a017781479f9a428e897b914a637ea1a2e92ece21c8d834600d00bb1bbe6"
  VITE_CLOUD_RUN_URL = "https://maps-250085264089.africa-south1.run.app"
  VITE_CLOUD_RUN_URL_ALTERNATIVE = "https://maps-3ongv2xd5a-bq.a.run.app"
  VITE_WIALON_SESSION_TOKEN = "c1099bc37c906fd0832d8e783b60ae0dD9D1A721B294486AC08F8AA3ACAC2D2FD45FF053"
  VITE_WIALON_API_URL = "https://hst-api.wialon.com"
  VITE_WIALON_LOGIN_URL = "https://hosting.wialon.com/?token=c1099bc37c906fd0832d8e783b60ae0dD9D1A721B294486AC08F8AA3ACAC2D2FD45FF053&lang=en"
  VITE_GOOGLE_MAPS_API_KEY = "AIzaSyAgScPnzBI-6vKoL7Cn1_1mkhvCI54chDg"
  VITE_MAPS_SERVICE_URL = "https://maps-250085264089.africa-south1.run.app//=AIzaSyAgScPnzBI-6vKoL7Cn1_1mkhvCI54chDg"
  VITE_MAPS_DOCKER_SERVICE_URL = "https://maps-250085264089.africa-south1.run.appafrica-south1-docker.pkg.dev/mat1-9e6b3/cloud-run-source-deploy/maps@sha256:994cecbac15d657e4e1401132b32970bafaa64d6b923294f629636543b551a2c"
  VITE__GOOGLE_MAPS_EMBED_URL = "https://www.google.com/maps/embed/v1/place?key=AIzaSyAgScPnzBI-6vKoL7Cn1_1mkhvCI54chDg"
  VITE_SERVICE_ACCOUNT_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCSftyXJgpaQ0Ji\nZ/k1xTjKhcTwgOxmnCpIPx3rST/zlwCdf3Gf8Gdzkf68C5rYg7fhg8IwicrmU4+q\n5DNwqIvwybaQbUV+IX+oCq44fYluLurDq5+ZLm7PxjYEyLBF+kVn5rbmjeI+1tWH\nkAqpMpAdX7+CgJr3Ue85c47Vi5k1OBEeHLRNqiv0Ms0EeEJ5FaZxl1SyUjl6LlBL\nS/nx8C5mR9fta0LiQCmfgYNFLUNlC8uS/vaGHdvMJPl45PzBItH+o5zOAaL5Swl0\ns0h1LAd+CBBhzA4IeQURhuaeWsiH8oW6R56bjx0C5onyoTzqzCFDOz2xRW7Zb8N9\nH2s4xcg5AgMBAAECggEACxaFyv1uuWn/lWvt94FJ1P9Wuobhjbsqcp0vXiqFSAJB\nAkq9/odvRxaw54n/0n02vt+OhEa7qB8BP+OllpR1Qhh8ZFZW9Q7jRwRm7yDmVOQB\nciW0bt9ONRT5K/fGKsfAdtamN5Fb41p2nzv6aJfKg2SmvcGO6SMHFqu9zwExy46p\nU4QiE2o+4rdnFRKaIrsuzPxwYzLrKByB0mWj/y9kY07S2J/9ftV283hPq3hTD2H4\n78dpeaNXODM/6HHrIUUiGLM1jQSLS4jakbonNq42BaZ5e31KbWrir3MuQvoStBGY\nU62aoJqDHrbvLjO5YrAhvoQRMPxbBvwzWNumLLxqgQKBgQDNvHRzQKIYAYyH6N+V\nN9TjBDVK7d5RkIPM7M3W0dmrjQSMyxUWRQiyNvRVN95TThxU3sr4k6wgYQsV7iFH\nU5WBGo/jf6L3VpUo9VzCjEHbXBvSCcvucDe4aE6qFrLO8/stCjeKqQVel71B6oqP\n2n+sVhNSAEeyFcB0ueG7MeLYgQKBgQC2SUSD1JmRSelxaLDTUzw1Dhz/j6DH64qV\nYra0xmJir5p96eDcXWDeMpMEdBnS/aOMul2C3rGoPlae32ffgV6DdP4ECYMVdK4x\n2tXxO52X8cWU3+LDHrm8lWiigEwo3s2el0f5W6ozZ41h6A6ldLP85uvFyCX1nrOe\nhXcWiOXTuQKBgQCTJgk8LaxB80mqI5tWxLoVLPtY/k0WlYBPX8fRsAI5uwDYGqCY\nbwPLQ5b6JJ11g9artTYDGMvx1LbzFoDi3Rt/XZowoyfSNDE3PFb+Jwcrd/PGBI/B\nmK2hzakF6no1nze1fStAl6dpgqowrSoxvZu3jVEAQ4cEDp66XgDfvMx9AQKBgQCb\nzeQSChV4aYRuutzow6wibP28MjdqqZi6NrWTrj1JvG6AUPcxY174jKG8nL+157Vz\nA5gJ0+5lr2K6SJmwIBN4qPa03Kx+Gk0Jr9JNbnc0+CG5LePUgt6eodXdj2uJQ2bc\nttF+ASto5ImjtYVPRoDRGU9MrdZEKnG8fLddO4W1gQKBgG6ITERMZjBrgo7AHkHm\nKOL99I2/+g5+9S/Ss+qD7ivIKFMbBmzFk4tnW//XB0+ATLmLSkpxcLBEVD9l/Flq\n3iP7whqO3LrxuEN7C5C/KmQZjbgeg5ylzMaqxG6BbDdnjGDWSFWgWzkO7FFFVEmc\nxeMDJh9JowhnRh/6MBOIuBfT\n-----END PRIVATE KEY-----\n"
  VITE_SERVICE_ACCOUNT_PRIVATE_KEY_ID = "036a90e4691c595a348aabbe6515d8291acd6574"
  VITE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@mat1-9e6b3.iam.gserviceaccount.com"
  VITE_CLIENT_ID = "101330162184304566760"
  VITE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
  VITE_TOKEN_URI = "https://oauth2.googleapis.com/token"
  VITE_AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
  VITE_CLIENT_X509_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40mat1-9e6b3.iam.gserviceaccount.com"
  VITE_UNIVERSE_DOMAIN = "googleapis.com"
  VITE_FIREBASE_CONFIG = "{\"apiKey\":\"AIzaSyBtq7Z6qqaVmb22d3aNcwNiqkrbGtIhJ7g\",\"authDomain\":\"mat1-9e6b3.firebaseapp.com\",\"databaseURL\":\"https://mat1-9e6b3-default-rtdb.firebaseio.com\",\"projectId\":\"mat1-9e6b3\",\"storageBucket\":\"mat1-9e6b3.appspot.com\",\"messagingSenderId\":\"250085264089\",\"appId\":\"1:250085264089:web:51c2b209e0265e7d04ccc8\",\"measurementId\":\"G-YHQHSJN5CQ\"}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
