[build]
  base = "/"
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Firebase configuration
  # Note: In production, set these in the Netlify UI instead of this file
  NODE_VERSION = "18.16.0"
  
  # Environment variables for build
  VITE_FIREBASE_API = "${VITE_FIREBASE_API}"
  VITE_FIREBASE_AUTH_DOMAIN = "${VITE_FIREBASE_AUTH_DOMAIN}"
  VITE_FIREBASE_DATABASE_URL = "${VITE_FIREBASE_DATABASE_URL}"
  VITE_FIREBASE_PROJECT_ID = "${VITE_FIREBASE_PROJECT_ID}"
  VITE_FIREBASE_STORAGE_BUCKET = "${VITE_FIREBASE_STORAGE_BUCKET}"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "${VITE_FIREBASE_MESSAGING_SENDER_ID}"
  VITE_FIREBASE_APP_ID = "${VITE_FIREBASE_APP_ID}"
  VITE_FIREBASE_MEASUREMENT_ID = "${VITE_FIREBASE_MEASUREMENT_ID}"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
